name: Run molecule

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  molecule-test:
    name: Molecule Test (${{ github.actor == 'dependabot[bot]' && 'Github' || 'Hifiberry' }})
    if: |
      github.event_name == 'push' ||
      github.event.pull_request.head.repo.full_name == github.repository
    runs-on: >-
      ${{ github.actor == 'dependabot[bot]' && 'ubuntu-latest' ||
          fromJSON('["self-hosted", "linux", "ARM64", "hifiberry"]') }}
    strategy:
      fail-fast: false
      matrix:
        scenario:
          - default
        distro:
          - debian12
        include:
          - distro: debian12
            image: geerlingguy/docker-debian12-ansible:latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Setup python (only on Github)
        if: github.actor == 'dependabot[bot]'
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install Molecule and Dependencies (only on Github)
        if: github.actor == 'dependabot[bot]'
        run: |
          python -m pip install --upgrade pip
          pip install "molecule[docker]" "molecule-plugins[docker]" ansible-lint

      - name: Add binary path to the runner (only on Raspberry)
        if: github.actor != 'dependabot[bot]'
        run: echo "/home/pi/.local/bin" >> $GITHUB_PATH

      - name: Run molecule
        run: molecule --base-config molecule/config.yml test -s ${{ matrix.scenario }}
        env:
          PROVISIONER_SKIP_TAGS: ${{ github.actor == 'dependabot[bot]' && 'hifiberry-only' || 'tag-does-not-exist' }}
          PLATFORMS_NETWORK_MODE: ${{ github.actor == 'dependabot[bot]' && 'bridge' || 'host' }} 
          PLATFORMS_PRIVILEGED: ${{ github.actor == 'dependabot[bot]' && 'false' || 'true' }}
          PLATFORMS_SND_DEV_PATH: ${{ github.actor == 'dependabot[bot]' && '/tmp/dummy-snd' || '/dev/snd' }}
          PLATFORMS_SYSTEM_DBUS_SOCKET: ${{ github.actor == 'dependabot[bot]' && '/tmp/dummy-dbus' || '/var/run/dbus/system_bus_socket' }}
          MOLECULE_DISTRO: ${{ matrix.distro }}
          MOLECULE_IMAGE: ${{ matrix.image }}
